### ISSUE TITLE
NoneType is not iterable

### ISSUE THREAD

**Issue by sils** [coala-analyzer/coala-gedit#11]
```
[ERROR][11:01:38 AM] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/lasse/.local/share/gedit/plugins/coala_gedit/CoalaViewActivatable.py", line 34, in <lambda>
    self.view.get_buffer().connect("saved", lambda x: self.analyze())
  File "/home/lasse/.local/share/gedit/plugins/coala_gedit/CoalaViewActivatable.py", line 91, in analyze
    self.show_result(result)
  File "/home/lasse/.local/share/gedit/plugins/coala_gedit/CoalaViewActivatable.py", line 60, in show_result
    if not isinstance(result.line_nr, int):
AttributeError: 'Result' object has no attribute 'line_nr'
```

**Comment by sils** [comment]
done i nhttps://github.com/coala-analyzer/coala-gedit/pull/10
